#PRACTICO 4- EJERCICIO 1
#ESCRIBE UN NUMERO POR LINEA, DEL 0 AL 100
#EL RANGO SE ESCRIBE 0, QUE ES EL PRIMER NUMERO TOMA Y 101 PORQUE EL ALGORITMO TOMA EL ANTERIOR, 100
for x in range (0,101):
    print(x)
print("Fin programa")